# sim settings, the rockets themselves are configured in rocket.yaml

time_step: 0.01   # seconds
step_delay: 0.001  # the time in between steps the sim stops to take a break (for visualization purposes)
max_time: 100000       # simulation lifetime, seconds (0 = run forever)

# other body gravity
moon_gravity: true   # include moon gravity
sun_gravity: true    # include sun gravity
ephemeris: config/de440s.bsp    # JPL DE440
epoch: "2026-10-10T12:00:00"    # UTC date and time at sim start

# aerodynamics
drag: true
